Repository beam-community/stripity-stripe, pull requests merged in 2018-06, with the labels that each got.

#371 add oauth and api tests w/ mox
  .travis.yml
  lib/stripe/api.ex
  lib/stripe/connect/oauth.ex
  mix.exs
  mix.lock
  test/stripe/api_test.exs
  test/stripe/connect/oauth_test.exs
  test/test_helper.exs
Labels: 2.0, blocked

#380 BUGFIX - improve plan struct
  lib/stripe/subscriptions/plan.ex
  test/stripe/subscriptions/plan_test.exs
Labels: bug, enhancement

#382 Update create card spec
  lib/stripe/payment_methods/card.ex
Labels: 2.0, enhancement

#384 update read me
  README.md
Labels: 2.0, enhancement

#386 Add `params` argument to Subscription.delete/2
  lib/stripe/subscriptions/subscription.ex
  test/stripe/subscriptions/subscription_test.exs
Labels: 2.0, enhancement

#390 Update api_version to 2018-05-21
  lib/stripe/api.ex
  lib/stripe/relay/product.ex
  lib/stripe/subscriptions/product.ex
  lib/stripe/subscriptions/subscription.ex
Labels: 2.0, enhancement

#391 Add `account` field to Event
  lib/stripe/core_resources/event.ex
  test/fixtures/event_with_customer.json
  test/stripe/converter_test.exs
Labels: 2.0, enhancement

#393 Add support for object expansion
  README.md
  lib/stripe/api.ex
  lib/stripe/core_resources/balance.ex
  lib/stripe/core_resources/charge.ex
  lib/stripe/core_resources/customer.ex
  lib/stripe/core_resources/dispute.ex
  lib/stripe/core_resources/payout.ex
  lib/stripe/core_resources/refund.ex
  lib/stripe/request.ex
  test/stripe/core_resources/charge_test.exs
  test/stripe/request_test.exs
Labels: 2.0, enhancement, in progress
