Repository beam-community/stripity-stripe, pull requests merged in 2019-09, with the labels that each got.

#535 CHANGELOG 2.5.0
  CHANGELOG.md
Labels: ready to merge

#522 Add support for SetupIntent
  .travis.yml
  lib/stripe/converter.ex
  lib/stripe/core_resources/setup_intent.ex
  lib/stripe/subscriptions/subscription.ex
  mix.exs
  test/stripe/core_resources/setup_intent_test.exs
  test/stripe/util_test.exs
Labels: 2.0, enhancement

#540 CHANGELOG 2.6.0
  CHANGELOG.md
Labels: 2.0, enhancement

#546 Add idempotent requests
  lib/stripe/api.ex
  test/stripe/api_test.exs
Labels: 2.0, enhancement

#547 CHANGELOG 2.7
  CHANGELOG.md
  mix.exs
Labels: 2.0
