Repository beam-community/stripity-stripe, pull requests merged in 2019-05, with the labels that each got.

#487 Implement `assert_stripe_requested/3`
  lib/stripe/payment_methods/bank_account.ex
  test/stripe/connect/account_test.exs
  test/stripe/connect/fee_refund_test.exs
  test/stripe/connect/transfer_reversal_test.exs
  test/stripe/core_resources/charge_test.exs
  test/stripe/core_resources/customer_test.exs
  test/stripe/core_resources/dispute_test.exs
  test/stripe/core_resources/payment_intent_test.exs
  test/stripe/core_resources/payout_test.exs
  test/stripe/relay/order_test.exs
  test/stripe/relay/product_test.exs
  test/stripe/relay/sku_test.exs
  test/stripe/subscriptions/invoice_test.exs
  test/stripe/subscriptions/invoiceitem_test.exs
  test/stripe/subscriptions/plan_test.exs
  test/stripe/subscriptions/product_test.exs
  test/stripe/subscriptions/subscription_item_test.exs
  test/stripe/subscriptions/subscription_test.exs
  test/stripe/subscriptions/usage_test.exs
  test/support/stripe_case.ex
Labels: enhancement

#498 Format mix.exs to pass CI
  mix.exs
Labels: 2.0

#495 Add PaymentMethods module, with struct, list/2, attach/2, detach/2
  lib/stripe/converter.ex
  lib/stripe/payment_methods/payment_method.ex
  test/stripe/payment_methods/payment_method_test.exs
Labels: needs code review

#492 Add CreditNote api calls
  lib/stripe/converter.ex
  lib/stripe/subscriptions/credit_note.ex
  test/stripe/subscriptions/credit_note_test.exs
Labels: 2.0, enhancement

#480 Add support for Subscription Schedules
  lib/stripe/converter.ex
  lib/stripe/subscriptions/subscription.ex
  lib/stripe/subscriptions/subscription_schedule.ex
  test/stripe/subscriptions/subscription_schedule_test.exs
Labels: 2.0, enhancement

#493 Add Stripe Issuing
  lib/stripe/converter.ex
  lib/stripe/issuing/authorization.ex
  lib/stripe/issuing/card.ex
  lib/stripe/issuing/card_details.ex
  lib/stripe/issuing/cardholder.ex
  lib/stripe/issuing/dispute.ex
  lib/stripe/issuing/transaction.ex
  lib/stripe/issuing/types.ex
  lib/stripe/types.ex
  lib/stripe/util.ex
  test/stripe/issuing/authorization_test.exs
  test/stripe/issuing/card_details_test.exs
  test/stripe/issuing/card_test.exs
  test/stripe/issuing/cardholder_test.exs
  test/stripe/issuing/dispute_test.exs
  test/stripe/issuing/transaction_test.exs
Labels: 2.0, enhancement
