Repository beam-community/stripity-stripe, pull requests merged in 2020-06, with the labels that each got.

#605 Added Terminal functionality
  lib/stripe/converter.ex
  lib/stripe/terminal/connection_token.ex
  lib/stripe/terminal/location.ex
  lib/stripe/terminal/reader.ex
  lib/stripe/util.ex
  mix.exs
  test/stripe/terminal/connection_token_test.exs
  test/stripe/terminal/location_test.exs
  test/stripe/terminal/reader_test.exs
Labels: 2.0, enhancement

#609 Add price to Subscription
  lib/stripe/subscriptions/line_item.ex
  lib/stripe/subscriptions/subscription.ex
  lib/stripe/subscriptions/subscription_item.ex
  lib/stripe/subscriptions/subscription_schedule.ex
Labels: 2.0, enhancement

#610 Allow creating refunds by payment intent or charge.
  lib/stripe/core_resources/refund.ex
Labels: 2.0, enhancement

#613 Fix multiple Stripe-Version headers when creating ephemeral key
  lib/stripe/ephemeral_key.ex
Labels: 2.0, bug, enhancement

#614 VERSION BUMP 2.9.0
  CHANGELOG.md
  mix.exs
Labels: 2.0
